project_id = "dexrrbbpeidcxoynkyrt"

[auth]
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[functions.send-verification-email]
verify_jwt = false

[functions.create-payment-preference]
verify_jwt = true

[functions.create-business-subscription]
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false

[functions.release-escrow]
verify_jwt = true

[functions.verify-payment-status]
verify_jwt = true

[functions.create-master-subscription]
verify_jwt = true

[functions.create-master-subscription-payment]
verify_jwt = true

[functions.create-business-subscription-payment]
verify_jwt = true

[functions.create-marketplace-payment]
verify_jwt = true

[functions.create-booking-payment]
verify_jwt = true

[functions.create-contract-payment]
verify_jwt = true

[functions.send-founder-welcome-email]
verify_jwt = true

[functions.filter-chat-message]
verify_jwt = true

[functions.register-master]
verify_jwt = false

[functions.register-client]
verify_jwt = false

[functions.search-master]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = true

[functions.manage-user-subscription]
verify_jwt = true
